# Generated by Django 4.2.5 on 2023-10-11 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
