# Generated by Django 4.2.5 on 2023-10-12 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
