# Generated by Django 4.2.5 on 2023-10-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255, unique=True)),
                ('connection_technology', models.CharField(choices=[('FTTB', 'FTTB'), ('FTTC', 'FTTC'), ('FTTH', 'FTTH'), ('DOCSIS', 'DOCSIS')], max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
